import { useEffect, useRef, useState } from 'react';
import { Icon } from '../components/Icons.jsx';
import { validateLetter } from '../content/validateContent.js';
import { AudioReviewPanel } from '../components/AudioReviewPanel.jsx';
import { DraftModelReview } from '../components/DraftModelReview.jsx';
import { matchAwards } from '../game/scoring.js';
import { downloadJson as download } from '../platform/download.js';
function CopyThumbnail({ copy }) {
  return <svg viewBox="0 0 1000 1000" className="copy-thumbnail" role="img" aria-label={`Salinan ${copy.letterId} untuk pemerhatian guru`}>
    {copy.ink.map((line,i) => <path key={i} d={line.map((p,j) => `${j ? 'L' : 'M'} ${p.x} ${p.y}`).join(' ')} fill="none" stroke="#276252" strokeWidth="14" strokeLinecap="round" strokeLinejoin="round"/>)}
  </svg>;
}
export function TeacherScreen({ letters, progress, store, matchStore, audio, diagnostic, preview, practiceMode, onPracticeMode, adjustment, onAdjustment, onPreview, onRefresh, onBack, onLetter }) {
  const matches = matchStore.read().matches;
  const [notice, setNotice] = useState('');
  const [resetConfirm, setResetConfirm] = useState(false);
  const [recording, setRecording] = useState(null);
  const objectUrl = useRef(null);
  useEffect(() => () => { audio.stop(); if (objectUrl.current) URL.revokeObjectURL(objectUrl.current); }, [audio]);
  const ready = letters.filter(l => validateLetter(l).ready).length;
  const ownerApproved = letters.filter(l => l.geometry.status === 'approved' && l.geometry.review?.kind === 'projectOwner').length;
  const availableAudio = letters.filter(l => l.audio.name.src).length;
  const approvedAudio = letters.filter(l => l.audio.name.status === 'approved').length;
  function chooseRecording(event) {
    const file = event.target.files?.[0]; if (!file) return;
    if (file.size > 15 * 1024 * 1024 || !/\.(mp3|wav|ogg|m4a)$/i.test(file.name)) { setNotice('Pilih rakaman audio kurang daripada 15 MB.'); return; }
    audio.stop(); if (objectUrl.current) URL.revokeObjectURL(objectUrl.current);
    objectUrl.current = URL.createObjectURL(file);
    setRecording({ src: objectUrl.current, status: 'draft' });
    setNotice('Rakaman dipilih. Tekan Mainkan untuk mendengar.');
  }
  async function audition() {
    const result = await audio.play(recording, { preview: true });
    setNotice(result.ok ? 'Rakaman pratonton dimainkan. Fail ini belum disimpan atau diluluskan.' : result.reason === 'blocked' ? 'Audio tidak dapat dimainkan. Pelayar meminta tindakan pengguna; tekan Mainkan untuk cuba semula.' : result.reason === 'unsupported' ? 'Pelayar ini tidak menyokong rakaman ini. Cuba format MP3 atau WAV pada pelayar lain.' : 'Audio tidak dapat dimainkan. Cuba format MP3 atau WAV.');
  }
  return <main className="teacher-page page-enter">
    <button className="text-button back-button" onClick={onBack}><Icon name="back" size={18}/>Kembali</button>
    <div className="garden-heading"><div><span className="eyebrow">UNTUK GURU & PENJAGA</span><h1>Ruang guru</h1><p>Pantau cubaan, semak kandungan, dan sediakan suara pembelajaran.</p></div><span className="teacher-tag"><Icon name="teacher"/>Disimpan pada peranti ini</span></div>
    <div className="teacher-stat-grid"><div><strong>{letters.length}</strong><span>huruf dalam katalog</span></div><div><strong>{letters.filter(l => l.geometry.strokes.length).length}</strong><span>model huruf untuk pratonton</span></div><div><strong>{ready}</strong><span>pelajaran sedia untuk murid</span></div><div><strong>{progress.attempts.length}</strong><span>cubaan jejak disimpan</span></div></div>
    <DraftModelReview letters={letters} onLetter={onLetter}/>
    <section className="teacher-panel"><h2>Pilihan latihan</h2>
      <label className="field-label" htmlFor="practice-mode">Jenis latihan</label><select id="practice-mode" value={practiceMode} onChange={e => onPracticeMode(e.target.value)}><option value="play">Jejak Ceria · dengan bantuan</option><option value="guided">Berpandu · jejak terkawal</option><option value="precision">Kurang panduan · jejak terkawal</option></select>
      <p>Jejak Ceria mengisi laluan dengan warna sebagai bantuan. Jika tersasar, kemajuan berhenti sekejap dan boleh disambung tanpa memadam kerja yang sudah diterima. Pad titik ialah tindakan bantuan, bukan ukuran ketepatan sentuhan pada huruf.</p>
      <p>Dalam latihan terkawal, dakwat ialah gerakan sebenar yang sah. Gerakan tersasar dibatalkan dan perlu diulang selepas mengangkat jari. Pilihan ini digunakan untuk cubaan baharu; rekod lama tidak ditukar.</p>
      <p className="small-muted">Ralat purata merangkumi segmen yang diterima sepanjang cubaan. Gerakan tersasar turut direkodkan. Dalam Jejak Ceria, liputan diukur sebelum isian akhir paparan; warna penuh bukan bukti tulisan bebas. Bantuan kecil pada selekoh rapat turut direkodkan dalam diagnostik. Rekod lama kekal sebagai legacy-v1.</p></section>
    <div className="teacher-columns"><section className="teacher-panel"><h2>Mod penggunaan</h2><p>{ownerApproved ? `${ownerApproved} model huruf telah diluluskan oleh pemilik projek. ${availableAudio} rakaman nama tersedia untuk semakan; semakan guru Jawi bernama belum direkodkan.` : 'Model pilot ialah draf pembangunan. Bentuk tulisan, arah, urutan dan audio masih memerlukan semakan guru Jawi sebelum digunakan sebagai bahan pengajaran.'}</p>
      <button className="button button-primary" onClick={onPreview}><Icon name="pen"/>Buka pratonton dewasa</button>
      <p className="small-muted">Pratonton {preview ? 'aktif' : 'belum aktif'}. Tiada kelulusan kandungan dibuat melalui butang ini.</p>
      <label className="field-label" htmlFor="adjustment">Toleransi latihan berpandu</label><select id="adjustment" value={adjustment} onChange={event => onAdjustment(event.target.value)}><option value="standard">Standard pembangunan</option><option value="support">Bantuan tambahan (+8 unit)</option></select>
      <p className="small-muted">Profil dikunci sepanjang cubaan. Mod kurang panduan tidak dilonggarkan. Nilai ini cadangan kejuruteraan, bukan standard KPM.</p>
    </section><section className="teacher-panel"><h2>Rakaman & kemajuan</h2><p>{availableAudio ? `${availableAudio} rakaman nama huruf tersedia untuk didengar. ${approvedAudio} rakaman diluluskan; contoh bunyi belum ditambah.` : 'Rakaman nama huruf dan contoh bunyi masih belum tersedia.'} Pilih fail sendiri untuk membandingkan rakaman.</p>
      <label className="file-button"><Icon name="sound"/>Pilih rakaman pratonton<input type="file" accept="audio/mpeg,audio/wav,audio/ogg,audio/mp4,.mp3,.wav,.ogg,.m4a" onChange={chooseRecording}/></label>
      {recording && <button className="button button-soft recording-replay" onClick={audition}><Icon name="play" size={18}/>Mainkan rakaman dipilih</button>}
      {notice && <p role="status" className="audio-notice">{notice}</p>}
      <div className="teacher-buttons"><button className="button button-outline" onClick={() => download('taman-jawi-kemajuan.json', JSON.stringify({ exportVersion: 2, progress: store.read(), matches: matchStore.export() }, null, 2))}><Icon name="download" size={18}/>Eksport kemajuan</button><button className="text-button" onClick={() => setResetConfirm(true)}>Padam rekod</button></div>
      {resetConfirm && <div className="reset-confirm" role="group" aria-label="Sahkan pemadaman"><p>Padam semua profil, cubaan, salinan dan rekod cabaran Solo / Duo pada pelayar ini?</p><button className="button button-outline" onClick={() => { store.reset(); matchStore.reset(); onRefresh(); setResetConfirm(false); }}>Ya, padam rekod</button><button className="text-button" onClick={() => setResetConfirm(false)}>Batal</button></div>}
      <p className="small-muted">{store.isAvailable() && matchStore.isAvailable() ? 'Kemajuan kekal dalam pelayar ini dan tidak disegerakkan ke peranti lain.' : 'Storan pelayar tidak tersedia. Rekod sesi ini disimpan sementara; sila eksport sebelum menutup.'} Salinan dihadkan kepada 12 hasil terkini; cabaran kepada 50 rekod terkini.</p>
    </section></div>
    <AudioReviewPanel letters={letters} audio={audio}/>
    <section className="teacher-panel"><h2>Cabaran Solo & Duo</h2><p>Jejak Ceria dengan bantuan. Markah masa dan trofi ialah ganjaran permainan, bukan ukuran penguasaan KPM. Cabaran terhenti tidak memberikan trofi.</p>{matches.length ? <div className="table-scroll"><table><thead><tr><th>Tarikh / pemain</th><th>Cabaran</th><th>Markah</th><th>Trofi</th><th>Henti / peraturan</th></tr></thead><tbody>{matches.slice().reverse().map(match => {
      const awards = matchAwards(match.mode, match.rounds, match.profiles.length);
      return <tr key={match.id}><td>{match.profiles.join(' / ')}<small>{new Date(match.timestamp).toLocaleString('ms-MY')}</small></td><td>{match.mode === 'duo' ? 'Duo 1v1' : 'Solo'} · {match.status === 'completed' ? 'Selesai' : 'Dihentikan'}<small>{match.rounds.length}/{match.letterIds.length} pusingan · {match.limitMs / 1000} saat</small></td><td>{awards.totals.join(' / ')}</td><td>{match.status === 'completed' && awards.trophy ? `${awards.shared ? 'Bersama · ' : ''}${awards.winners.map(slot => match.profiles[slot]).join(' / ')} · ${awards.trophy}` : 'Tiada'}</td><td>{match.pauseCount} kali berhenti<small>{match.rulesVersion}</small></td></tr>;
    })}</tbody></table></div> : <p className="empty-state">Cabaran yang selesai atau dihentikan akan dipaparkan di sini.</p>}</section>
    <section className="teacher-panel"><h2>Kandungan & semakan</h2><p>37 huruf merujuk bank kajian DBP. Pilihan 12 huruf pilot ialah cadangan pembangunan. Tracing tidak menggantikan penilaian bacaan atau penyalinan perkataan PI 1.5.2–1.5.3.</p><div className="table-scroll"><table><thead><tr><th>Huruf</th><th>Model</th><th>Rakaman nama</th><th>Versi</th><th>Pratonton</th></tr></thead><tbody>{letters.map(letter => <tr key={letter.id}><td><span className="jawi table-glyph" dir="rtl" lang="ms-Arab">{letter.glyph}</span>{letter.labelMs}</td><td><span className={`status-chip ${letter.geometry.status}`} title={letter.geometry.review ? `${letter.geometry.review.reviewer} · ${letter.geometry.review.date} · versi ${letter.geometry.review.revision}` : undefined}>{letter.geometry.status === 'approved' ? letter.geometry.review?.kind === 'projectOwner' ? 'Diluluskan · pemilik projek' : 'Diluluskan' : letter.geometry.strokes.length ? 'Draf · perlu semakan' : 'Model belum tersedia'}</span>{letter.geometry.status === 'approved' && <small>{letter.geometry.review.date}</small>}</td><td>{letter.audio.name.status === 'approved' ? 'Diluluskan' : letter.audio.name.src ? 'Draf suara · perlu semakan' : 'Belum tersedia'}</td><td>{letter.contentVersion}</td><td><button className="text-button" disabled={!letter.geometry.strokes.length} onClick={() => onLetter(letter)}>Buka<Icon name="arrow" size={16}/></button></td></tr>)}</tbody></table></div></section>
    <section className="teacher-panel"><h2>Cubaan terkini</h2><p>Peratus liputan ialah ukuran geometri dalam aktiviti ini, bukan TP KPM atau penguasaan tulisan bebas.</p>{!progress.attempts.length ? <p className="empty-state">Cubaan yang selesai akan dipaparkan di sini.</p> : <div className="table-scroll"><table><thead><tr><th>Profil / huruf</th><th>Aktiviti</th><th>Liputan</th><th>Ralat purata</th><th>Gerakan tersasar</th><th>Bantuan / ulang</th><th>Versi / input</th></tr></thead><tbody>{progress.attempts.slice(-30).reverse().map(attempt => <tr key={attempt.id}><td>{attempt.profile} · {attempt.letterId}<small>{new Date(attempt.timestamp).toLocaleString('ms-MY')}</small></td><td>{attempt.mode === 'play' ? 'Jejak Ceria · dengan bantuan' : attempt.mode === 'guided' ? 'Berpandu' : 'Kurang panduan'}{attempt.sessionType && <small>{attempt.sessionType === 'duo' ? 'Duo 1v1' : 'Cabaran Solo'} · pusingan {attempt.roundIndex + 1}</small>}{attempt.preview && <small>{attempt.geometryStatus === 'approved' ? 'Pratonton dewasa' : 'Pratonton draf'}</small>}</td><td>{Math.round(attempt.metrics.coverage * 100)}%</td><td>{attempt.metrics.meanError.toFixed(1)} unit</td><td>{Math.round(attempt.metrics.invalidTravel)} unit / {attempt.metrics.invalidEvents} kejadian</td><td>{attempt.assistance} / {attempt.retries}</td><td>{attempt.contentVersion} / {attempt.pointerType}<small>{attempt.toleranceProfile}</small><small>{attempt.interactionPolicy || 'legacy-v1'} · {attempt.mode === 'play' ? `${attempt.metrics.pauseEpisodes ?? 0} kali berhenti / ${attempt.metrics.resumeCount ?? 0} kali sambung` : `${attempt.metrics.blockedGestures ?? 0} gerak ditolak`}</small>{attempt.dotInputPolicy?.startsWith('validatedTap') && <small>Titik: bantuan sentuhan{attempt.metrics.equivalentDotActions ? ` / ${attempt.metrics.equivalentDotActions} pad` : ''}</small>}</td></tr>)}</tbody></table></div>}</section>
    {diagnostic && <section className="teacher-panel"><h2>Diagnostik sesi terakhir</h2><p>{diagnostic.timing?.samples || 0} sampel diproses. Purata pengendalian: {((diagnostic.timing?.totalMs || 0) / Math.max(1, diagnostic.timing?.samples || 0)).toFixed(2)} ms; maksimum: {(diagnostic.timing?.maxMs || 0).toFixed(2)} ms. Ini masa pengendalian JavaScript, bukan ukuran keseluruhan latensi skrin.</p><button className="button button-outline" onClick={() => download('taman-jawi-diagnostik.json', JSON.stringify(diagnostic, null, 2))}><Icon name="download"/>Eksport jejak sesi ini</button><p className="small-muted">Eksport ini mengandungi koordinat tulisan. Jejak diagnostik kekal dalam memori sehingga tindakan eksport.</p></section>}
    <section className="teacher-panel"><h2>Salinan untuk pemerhatian</h2><p>Hasil ini ialah tulisan sebenar pengguna. Tiada skor pengecaman tulisan bebas diberikan.</p><div className="copy-grid">{progress.copies.length ? progress.copies.slice().reverse().map(copy => <figure key={copy.id}><CopyThumbnail copy={copy}/><figcaption>{copy.profile} · {copy.letterId}<small>{new Date(copy.timestamp).toLocaleDateString('ms-MY')}</small></figcaption></figure>) : <p className="empty-state">Selepas jejak huruf, pilih “cuba salin sendiri”.</p>}</div></section>
  </main>;
}
