import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {deepStrictEqual,strictEqual} from 'node:assert';
import {nyaTipReviewCandidates} from '../src/content/reviewCandidates.js';
const root='output/verification/nya-approval';mkdirSync(root,{recursive:true});
const read=p=>JSON.parse(readFileSync(p,'utf8').replace(/^\uFEFF/,'')),hash=p=>createHash('sha256').update(readFileSync(p)).digest('hex');
const review=read('output/verification/nya-tip/inputs.json');
for(const [path,sha]of Object.entries(review.hashes).filter(([p])=>p.startsWith('src/')))strictEqual(hash(path),sha,path);
const path='src/content/letters.json',letters=read(path),proposals=read('output/verification/nya-tip/reviewed-proposals.json');
deepStrictEqual(proposals,nyaTipReviewCandidates(letters));strictEqual(proposals.length,1);
writeFileSync(`${root}/before-catalogue.json`,readFileSync(path));
writeFileSync(`${root}/reviewed-proposals.json`,JSON.stringify(proposals,null,2)+'\n');
writeFileSync(`${root}/review-browser-test.js`,readFileSync('tests/browser/nya-tip.spec.js'));
const approved=structuredClone(proposals[0].candidate);
approved.geometry.status='approved';approved.geometry.review={revision:4,reviewer:'Project owner (Codex user; name not supplied)',date:'2026-10-07',reference:'docs/CONTENT_APPROVALS.md#approval-of-nya-shorter-tip-2026-10-07',kind:'projectOwner'};
letters[letters.findIndex(letter=>letter.id==='nya')]=approved;
writeFileSync(path,JSON.stringify(letters,null,2)+'\n');
writeFileSync(`${root}/authorisation.json`,JSON.stringify({quote:'aprrove',question:'Approve the shorter Nya 4 on the right for normal lessons?',scope:'Promote exact reviewed Nya 4 geometry, retaining the bowl, three dots and audio.',date:'2026-10-07',reviewer:approved.geometry.review.reviewer,revision:4},null,2)+'\n');
console.log('Approved exact reviewed Nya 4; all 35 other entries and audio preserved.');
