import React from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource/noto-naskh-arabic/arabic-400.css';
import '@fontsource/noto-naskh-arabic/arabic-600.css';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/dm-sans/latin-700.css';
import '@fontsource/outfit/latin-400.css';
import '@fontsource/outfit/latin-500.css';
import '@fontsource/outfit/latin-600.css';
import './styles/theme.css';
import './styles/app.css';
import './styles/match.css';
import './styles/playground.css';
import './styles/book.css';
import App from './App.jsx';
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
